### PR TITLE
Add support for PIC32MZ devices

### PR DESCRIPTION
**Pull request by kferrari**
Hi,

Thanks a lot for this great tool. I added support for PIC32MZ devices (tested with PIC32MZ2048EFH100 only), where `config_data_addr` starts at `boot_rom_addr  | 0xFF00` and not `boot_rom_addr  | 0x2FF0`.

It is really the only thing that changed in the new `PIC32DevKit` class.

### CODE REVIEW

**Review by thotypous — CHANGES_REQUESTED** [review]
Thank you very much for your contribution!

Could you please try to inherit from PIC32DevKit (i.e. `class PIC32MZDevKit(PIC32DevKit):` instead of `class PIC32MZDevKit(DevKitModel):`) so that you don't need to copy code, just override the attributes? Then please test the new code with your kit and commit to your tree.

**Comment by kferrari** [comment]
You are of course absolutely right and that is a way cleaner solution. I made the suggested changes and verified it works with my device.

Please let me know if anything else catches your eye.

**Comment by kferrari** [comment]
Here we go. Sorry for the many commits. I had some additional changes and customisations and tried to commit clean without them. This messed some things up. Now I think all should be fine. Thanks again for all your work. You saved me a lot of trouble with this tool!

**Review by thotypous — APPROVED** [review]

**Comment by thotypous** [comment]
Thanks a lot!

**Pull request merged**
